### ISSUE TITLE
Chapter 03 - Code not consistent with book

### ISSUE THREAD

**Issue by neumannm** [PacktPublishing/Spring-5.0-By-Example#9]
In the book, on page 90, the new annotations for the domain classes `Category`, `News` and `User` are described that configure these classes for MongoDB persistence.
These annotations are not present in the code in this repository.
The code seems to be working nonetheless, which is very confusing.

**Comment by claudioed** [comment]
Hey @neumannm, you are right. The code will work at all because the spring framework will configure the mongo collection automatically in that version. But I would like to suggest you add the annotation to make things more clear for developers. I will create a PR as soon. Thank you for your feedback!!

**Comment by neumannm** [comment]
Thank you @claudioed for your timely response and your explanation.
Spring is so much magic. :)
